name: Deploy

on:
  workflow_run:
    workflows: [ "Checks" ]
    types:
    - completed

  push:
    branches:
    - '*'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: build image
      run: docker build -t annakor98/myimage .
    - name: push to Docker Hub
      run: docker push annakor98/myimage:latest
